/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.rasmaker.tpuno;

import javax.swing.JOptionPane;

/**
 *
 * @author Rodrigo
 */
public class Menu extends javax.swing.JFrame {

    Operadores operar = new Operadores();
    
    public Menu() {
        initComponents();
    }
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Ej1 = new javax.swing.JLabel();
        Num1 = new javax.swing.JTextField();
        mas = new javax.swing.JLabel();
        Num2 = new javax.swing.JTextField();
        igual = new javax.swing.JLabel();
        sumResultado = new javax.swing.JLabel();
        botonSumar = new javax.swing.JButton();
        Error = new javax.swing.JLabel();
        Num3 = new javax.swing.JTextField();
        Ej2 = new javax.swing.JLabel();
        igual1 = new javax.swing.JLabel();
        eleResultado = new javax.swing.JLabel();
        botonCuadrado = new javax.swing.JButton();
        Ej3 = new javax.swing.JLabel();
        Num4 = new javax.swing.JTextField();
        igual2 = new javax.swing.JLabel();
        pipResultado = new javax.swing.JLabel();
        BotonPie = new javax.swing.JButton();
        BotonPulgadas = new javax.swing.JButton();
        Ej4 = new javax.swing.JLabel();
        Num5 = new javax.swing.JTextField();
        Num6 = new javax.swing.JTextField();
        igual3 = new javax.swing.JLabel();
        hipResultado = new javax.swing.JLabel();
        BotonHipotenusa = new javax.swing.JButton();
        Ej5 = new javax.swing.JLabel();
        Num7 = new javax.swing.JTextField();
        igual4 = new javax.swing.JLabel();
        facResultado = new javax.swing.JLabel();
        botonFactorizar = new javax.swing.JButton();
        Ej6 = new javax.swing.JLabel();
        BotonVector = new javax.swing.JButton();
        Ej7 = new javax.swing.JLabel();
        BotonVector1 = new javax.swing.JButton();
        Ej8 = new javax.swing.JLabel();
        BotonVector2 = new javax.swing.JButton();
        Ej9 = new javax.swing.JLabel();
        BotonVector3 = new javax.swing.JButton();
        Ej10 = new javax.swing.JLabel();
        BotonVector4 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        Ej1.setText("Ejercicio 1:");

        mas.setText("+");

        Num2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Num2ActionPerformed(evt);
            }
        });

        igual.setText("=");

        sumResultado.setText("Resultado");

        botonSumar.setText("Suma");
        botonSumar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonSumarActionPerformed(evt);
            }
        });

        Error.setForeground(new java.awt.Color(255, 0, 0));

        Num3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Num3ActionPerformed(evt);
            }
        });

        Ej2.setText("Ejercicio 2:");

        igual1.setText("=");

        eleResultado.setText("Resultado");

        botonCuadrado.setText("Cuadrado");
        botonCuadrado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonCuadradoActionPerformed(evt);
            }
        });

        Ej3.setText("Ejercicio 3:");

        Num4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Num4ActionPerformed(evt);
            }
        });

        igual2.setText("=");

        pipResultado.setText("Resultado");

        BotonPie.setText("Pie");
        BotonPie.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonPieActionPerformed(evt);
            }
        });

        BotonPulgadas.setText("Pulgadas");
        BotonPulgadas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonPulgadasActionPerformed(evt);
            }
        });

        Ej4.setText("Ejercicio4:");

        Num5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Num5ActionPerformed(evt);
            }
        });

        Num6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Num6ActionPerformed(evt);
            }
        });

        igual3.setText("=");

        hipResultado.setText("Resultado");

        BotonHipotenusa.setText("Calcular");
        BotonHipotenusa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonHipotenusaActionPerformed(evt);
            }
        });

        Ej5.setText("Ejercicio5:");

        Num7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Num7ActionPerformed(evt);
            }
        });

        igual4.setText("=");

        facResultado.setText("Resultado");

        botonFactorizar.setText("Factorizar");
        botonFactorizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonFactorizarActionPerformed(evt);
            }
        });

        Ej6.setText("Ejercicio6:");

        BotonVector.setText("Ingresar");
        BotonVector.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonVectorActionPerformed(evt);
            }
        });

        Ej7.setText("Ejercicio7:");

        BotonVector1.setText("Ingresar");
        BotonVector1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonVector1ActionPerformed(evt);
            }
        });

        Ej8.setText("Ejercicio8:");

        BotonVector2.setText("Ingresar");
        BotonVector2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonVector2ActionPerformed(evt);
            }
        });

        Ej9.setText("Ejercicio9:");

        BotonVector3.setText("Ingresar");
        BotonVector3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonVector3ActionPerformed(evt);
            }
        });

        Ej10.setText("Ejercicio10:");

        BotonVector4.setText("Ingresar");
        BotonVector4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonVector4ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(Ej3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(Num4, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(igual2, javax.swing.GroupLayout.PREFERRED_SIZE, 8, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(pipResultado)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(BotonPie))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(Ej5)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(Num7, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(igual4, javax.swing.GroupLayout.PREFERRED_SIZE, 8, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(facResultado)
                                .addGap(239, 239, 239))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(Error)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(Ej4)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(Num5, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(Num6, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(igual3, javax.swing.GroupLayout.PREFERRED_SIZE, 8, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(hipResultado)))
                                .addGap(0, 0, Short.MAX_VALUE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(botonFactorizar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(BotonHipotenusa, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(BotonPulgadas, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(Ej2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(Num3, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(igual1, javax.swing.GroupLayout.PREFERRED_SIZE, 8, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(eleResultado))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(Ej1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(Num1, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(mas)
                                .addGap(12, 12, 12)
                                .addComponent(Num2, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(igual, javax.swing.GroupLayout.PREFERRED_SIZE, 8, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(sumResultado)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(botonCuadrado, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(botonSumar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(Ej6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(BotonVector)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(Ej10)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(BotonVector4))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(Ej7)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(BotonVector1))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(Ej9)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(BotonVector3))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(Ej8)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(BotonVector2)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Ej1)
                    .addComponent(Num1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(mas)
                    .addComponent(Num2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(igual)
                    .addComponent(sumResultado)
                    .addComponent(botonSumar))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Num3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Ej2)
                    .addComponent(igual1)
                    .addComponent(eleResultado)
                    .addComponent(botonCuadrado))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Ej3)
                    .addComponent(Num4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(igual2)
                    .addComponent(pipResultado)
                    .addComponent(BotonPie)
                    .addComponent(BotonPulgadas))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Num5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Num6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Ej4)
                    .addComponent(igual3)
                    .addComponent(hipResultado)
                    .addComponent(BotonHipotenusa))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Ej5)
                    .addComponent(Num7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(igual4)
                    .addComponent(facResultado)
                    .addComponent(botonFactorizar))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Ej6)
                    .addComponent(BotonVector))
                .addGap(15, 15, 15)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Ej7)
                    .addComponent(BotonVector1))
                .addGap(16, 16, 16)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Ej8)
                    .addComponent(BotonVector2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Ej9)
                    .addComponent(BotonVector3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Ej10)
                    .addComponent(BotonVector4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(Error))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void Num2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Num2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Num2ActionPerformed

    private void botonSumarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonSumarActionPerformed
        try{
            double n1 = Double.parseDouble(Num1.getText());
            double n2 = Double.parseDouble(Num2.getText());
            operar.sumar(n1, n2);
            sumResultado.setText(String.valueOf(operar.Resultado));
        }catch(NumberFormatException a){
            JOptionPane.showMessageDialog(null, "Error: el valor ingresado no es numérico.", "Error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_botonSumarActionPerformed

    private void Num3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Num3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Num3ActionPerformed

    private void botonCuadradoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonCuadradoActionPerformed
        try{
            double num = Double.parseDouble(Num3.getText());
            operar.cuadrado(num);
            eleResultado.setText(String.valueOf(operar.Resultado));
        }catch(NumberFormatException a){
            JOptionPane.showMessageDialog(null, "Error: el valor ingresado no es numérico.", "Error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_botonCuadradoActionPerformed

    private void Num4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Num4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Num4ActionPerformed

    private void BotonPieActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonPieActionPerformed
        try{
            double num = Double.parseDouble(String.valueOf(Num4.getText()));
            operar.compipul(num, 1);
            pipResultado.setText(String.valueOf(operar.Resultado));
        }catch(NumberFormatException a){
            JOptionPane.showMessageDialog(null, "Error: el valor ingresado no es numérico.", "Error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_BotonPieActionPerformed

    private void BotonPulgadasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonPulgadasActionPerformed
        try{
            double num = Double.parseDouble(String.valueOf(Num4.getText()));
            operar.compipul(num, 2);
            pipResultado.setText(String.valueOf(operar.Resultado));
        }catch(NumberFormatException a){
            JOptionPane.showMessageDialog(null, "Error: el valor ingresado no es numérico.", "Error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_BotonPulgadasActionPerformed

    private void Num5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Num5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Num5ActionPerformed

    private void Num6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Num6ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Num6ActionPerformed

    private void BotonHipotenusaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonHipotenusaActionPerformed
        try{
            double num = Double.parseDouble(String.valueOf(Num5.getText()));
            double num1 = Double.parseDouble(String.valueOf(Num6.getText()));
            operar.calcularHipotenusa(num, num1);
            hipResultado.setText(String.valueOf(operar.Resultado));
        }catch(NumberFormatException a){
            JOptionPane.showMessageDialog(null, "Error: el valor ingresado no es numérico.", "Error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_BotonHipotenusaActionPerformed

    private void Num7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Num7ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Num7ActionPerformed

    private void botonFactorizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonFactorizarActionPerformed
        try{
            double num = Double.parseDouble(String.valueOf(Num7.getText()));
            operar.factorial(num);
            facResultado.setText(String.valueOf(operar.Resultado));
        }catch(NumberFormatException a){
            JOptionPane.showMessageDialog(null, "Error: el valor ingresado no es numérico.", "Error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_botonFactorizarActionPerformed

    private void BotonVectorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonVectorActionPerformed
        try{
        int[] vector = new int[10];

        JOptionPane.showMessageDialog(null, "Ingresa 10 elementos numéricos:");

        for (int i = 0; i < vector.length; i++) {
            String input = JOptionPane.showInputDialog("Elemento " + (i + 1) + ":");
            vector[i] = Integer.parseInt(input);
        }

        JOptionPane.showMessageDialog(null, "Elementos precedidos por un cero:");

        for (int i = 1; i < vector.length; i++) {
            if (vector[i - 1] == 0) {
                for(int v = i; v< vector.length; v++){
                JOptionPane.showMessageDialog(null, vector[v]);}
            }
        }

        }catch(NumberFormatException a){
            JOptionPane.showMessageDialog(null, "Error: el valor ingresado no es numérico.", "Error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_BotonVectorActionPerformed

    private void BotonVector1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonVector1ActionPerformed
        try{
            int n = 10; // Tamaño del vector
            int[] vector = new int[n];

            vector[0] = 1; // Valor inicial

            for (int i = 1; i < n; i++) {
                vector[i] = i * vector[i - 1] + i * i;
            }

            StringBuilder message = new StringBuilder("Elementos del vector calculados:\n");

            for (int i = 0; i < n; i++) {
                message.append("A[").append(i + 1).append("] = ").append(vector[i]).append("\n");
            }

        JOptionPane.showMessageDialog(null, message.toString());
        }catch(NumberFormatException a){
            JOptionPane.showMessageDialog(null, "Error: el valor ingresado no es numérico.", "Error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_BotonVector1ActionPerformed

    private void BotonVector2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonVector2ActionPerformed
        int[] vector = new int[10];

    // Ingreso de elementos
    for(int i=0; i<vector.length; i++) {
      vector[i] = Integer.parseInt(JOptionPane.showInputDialog("Ingresar elemento " + (i+1)));
    }

    // Mostrar vector
    String mensajeVector = "Vector: \n";
    for(int num : vector) {
      mensajeVector += num + " ";
    }
    JOptionPane.showMessageDialog(null, mensajeVector);

    // Primer elemento menor que 0
    int indiceMenorQueCero = operar.buscarMenorQueCero(vector);
    String mensaje1 = "Primer índice menor que cero: " + indiceMenorQueCero;
    JOptionPane.showMessageDialog(null, mensaje1);

    // Mayor elemento
    int mayor = operar.buscarMayor(vector);  
    int posMayor = operar.indiceDelMayor(vector, mayor);
    String mensaje2 = "El mayor elemento es: " + mayor + " en la posición: " + posMayor;
    JOptionPane.showMessageDialog(null, mensaje2);
    
    }//GEN-LAST:event_BotonVector2ActionPerformed

    private void BotonVector3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonVector3ActionPerformed
        int[][] matriz = new int[10][10];

    // Generar matriz unidad
    operar.generarMatrizUnidad(matriz);

    // Mostrar matriz en JOptionPane
    String mensaje = "";
    for(int i=0; i<matriz.length; i++) {
      for(int j=0; j<matriz[i].length; j++) {
        mensaje += matriz[i][j] + " ";
      }
      mensaje += "\n";
    }

    JOptionPane.showMessageDialog(null, mensaje);

  
    }//GEN-LAST:event_BotonVector3ActionPerformed

    private void BotonVector4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonVector4ActionPerformed
        try{
        int[][] matriz = new int[5][10];
        int[] sumaFilas = new int[5];

        // Leer valores de la matriz
        for(int i=0; i<matriz.length; i++) {
          for(int j=0; j<matriz[i].length; j++) {
            matriz[i][j] = Integer.parseInt(JOptionPane.showInputDialog("Fila " + (i+1) + " Columna " + (j+1))); 
          }
        }

        // Calcular suma de cada fila
        for(int i=0; i<matriz.length; i++) {
          int suma = 0;
          for(int j=0; j<matriz[i].length; j++) {
            suma += matriz[i][j];  
          }
          sumaFilas[i] = suma;
        }
        // Calcular y obtener suma de filas

        String mensaje = "Suma de filas: ";
        for(int num: sumaFilas) {
          mensaje += num + " "; 
        }

        JOptionPane.showMessageDialog(null, mensaje);
        }catch(NumberFormatException a){
            JOptionPane.showMessageDialog(null, "Error: el valor ingresado no es numérico.", "Error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_BotonVector4ActionPerformed


    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Menu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BotonHipotenusa;
    private javax.swing.JButton BotonPie;
    private javax.swing.JButton BotonPulgadas;
    private javax.swing.JButton BotonVector;
    private javax.swing.JButton BotonVector1;
    private javax.swing.JButton BotonVector2;
    private javax.swing.JButton BotonVector3;
    private javax.swing.JButton BotonVector4;
    private javax.swing.JLabel Ej1;
    private javax.swing.JLabel Ej10;
    private javax.swing.JLabel Ej2;
    private javax.swing.JLabel Ej3;
    private javax.swing.JLabel Ej4;
    private javax.swing.JLabel Ej5;
    private javax.swing.JLabel Ej6;
    private javax.swing.JLabel Ej7;
    private javax.swing.JLabel Ej8;
    private javax.swing.JLabel Ej9;
    private javax.swing.JLabel Error;
    private javax.swing.JTextField Num1;
    private javax.swing.JTextField Num2;
    private javax.swing.JTextField Num3;
    private javax.swing.JTextField Num4;
    private javax.swing.JTextField Num5;
    private javax.swing.JTextField Num6;
    private javax.swing.JTextField Num7;
    private javax.swing.JButton botonCuadrado;
    private javax.swing.JButton botonFactorizar;
    private javax.swing.JButton botonSumar;
    private javax.swing.JLabel eleResultado;
    private javax.swing.JLabel facResultado;
    private javax.swing.JLabel hipResultado;
    private javax.swing.JLabel igual;
    private javax.swing.JLabel igual1;
    private javax.swing.JLabel igual2;
    private javax.swing.JLabel igual3;
    private javax.swing.JLabel igual4;
    private javax.swing.JLabel mas;
    private javax.swing.JLabel pipResultado;
    private javax.swing.JLabel sumResultado;
    // End of variables declaration//GEN-END:variables
}
